### ISSUE TITLE
Undeclared global "lines"

### ISSUE THREAD

**Issue by aerth** [Zeg9/minetest-skins#7]
```
Assignment to undeclared global "lines" inside a function at .../minetest_game/mods/minetest-skins/skins/players.lua:9.
```

Line 9: 

```
                lines = string.split(data,"\n")
```

**Comment by aerth** [comment]
Minetest 0.4.12-dev-5ebb423
Build info: VER=0.4.12-dev-5ebb423 BUILD_TYPE=Release RUN_IN_PLACE=1 USE_GETTEXT=0 USE_SOUND=0 USE_CURL=1 USE_FREETYPE=1 USE_LUAJIT=0 STATIC_SHAREDIR="."

**Comment by HybridDog** [comment]
https://gist.github.com/HybridDog/d359f4361c5c626b31dc

**Comment by aerth** [comment]
Thanks @HybridDog !
